on: [push]

name: Deployment

env:
  RUST_VERSION: 'nightly-2021-11-01'

jobs:
  native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ env.RUST_VERSION }}
        targets: 'wasm32-unknown-unknown'

    - name: Checkout the source code
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - name: Run all tests
      run: cargo test --all

    - name: Cleanup after tests
      run: cargo clean

    - name: Build optimized binary
      run: cargo build --release --verbose

    - uses: actions/upload-artifact@master
      with:
        name: frontier-${{ matrix.os }}-x86_64
        path: target/release/frontier-template-node

  runtime-benchmarks:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ env.RUST_VERSION }}
        targets: 'wasm32-unknown-unknown'

    - name: Checkout the source code
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - name: Build optimized binary for benchmarking
      run: cargo build --release --features runtime-benchmarks

    - uses: actions/upload-artifact@master
      with:
        name: frontier-runtime-benchmarks
        path: target/release/frontier-template-node
        retention-days: 1